#!/usr/bin/env bash
# cargo-cache-guard.sh — reclaim Rust target-dir space, safely.
#
# WHY: codex-rs/target accumulates across profiles (debug / release /
# fast-release) plus incremental caches. `cargo test` alone grows
# target/debug (incremental + test binaries) with no cleanup of its own. This
# guard prunes the safe-to-regenerate artifacts when the target dir or the
# filesystem crosses a threshold.
#
# SAFETY:
#   * NEVER runs while a build is active (any cargo/rustc process) — target/ is
#     off limits mid-build. It exits 0 without touching anything.
#   * Only ever removes cargo-regenerable artifacts under target/. It never
#     touches the deployed binary (~/.local/lib/ecodex) or source.
#   * Threshold-gated: a no-op unless target/ is large OR free space is low
#     (override with --force). Tier-1 (debug wipe) only under real pressure or
#     --aggressive, because it forces a full `cargo test` rebuild next time.
#
# Usage:
#   cargo-cache-guard.sh [--dry-run] [--force] [--aggressive]
#     --dry-run     report what would be freed; delete nothing
#     --force       run regardless of threshold (still build-safe)
#     --aggressive  also wipe target/debug (test-only artifacts)
#
# Env overrides:
#   CARGO_TARGET_DIR         target dir (default: <repo>/codex-rs/target)
#   CARGO_GUARD_MAX_TARGET_GB  prune when target exceeds this (default 24)
#   CARGO_GUARD_MIN_FREE_GB    prune when disk free below this (default 40)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_DIR="${CARGO_TARGET_DIR:-${REPO_ROOT}/codex-rs/target}"
MAX_TARGET_GB="${CARGO_GUARD_MAX_TARGET_GB:-24}"
MIN_FREE_GB="${CARGO_GUARD_MIN_FREE_GB:-40}"

DRY=0; FORCE=0; AGG=0
for a in "$@"; do
  case "$a" in
    --dry-run) DRY=1 ;;
    --force) FORCE=1 ;;
    --aggressive) AGG=1 ;;
    *) echo "[cargo-cache-guard] unknown arg: $a" >&2; exit 2 ;;
  esac
done

log() { echo "[cargo-cache-guard] $*"; }

# 1. SAFETY GATE — never operate while a build is running.
if pgrep -x cargo >/dev/null 2>&1 || pgrep -x rustc >/dev/null 2>&1; then
  log "build active (cargo/rustc running) — skipping; target/ is off limits mid-build"
  exit 0
fi

if [ ! -d "$TARGET_DIR" ]; then
  log "no target dir at $TARGET_DIR — nothing to do"
  exit 0
fi

gb_of() { du -sk "$1" 2>/dev/null | awk '{printf "%d", $1/1024/1024}'; }

target_gb="$(gb_of "$TARGET_DIR")"
free_gb="$(df -BG --output=avail "$TARGET_DIR" 2>/dev/null | tail -1 | tr -dc '0-9')"
free_gb="${free_gb:-9999}"
log "target=${target_gb}G free=${free_gb}G (thresholds: max_target=${MAX_TARGET_GB}G min_free=${MIN_FREE_GB}G)"

over=0
[ "$target_gb" -ge "$MAX_TARGET_GB" ] && over=1
[ "$free_gb" -le "$MIN_FREE_GB" ] && over=1
if [ "$FORCE" -ne 1 ] && [ "$over" -ne 1 ]; then
  log "under threshold — no action"
  exit 0
fi

rm_path() {
  local p="$1"
  [ -e "$p" ] || return 0
  local sz; sz="$(du -sh "$p" 2>/dev/null | awk '{print $1}')"
  if [ "$DRY" -eq 1 ]; then
    log "DRY would remove $p ($sz)"
  else
    log "removing $p ($sz)"
    rm -rf "$p"
  fi
}

# Tier 0 — incremental caches. Always safe; release/fast-release don't use them,
# and debug's just recompiles a touch slower next time.
for inc in "$TARGET_DIR"/*/incremental; do
  rm_path "$inc"
done

# Tier 1 — target/debug (test-only artifacts, regenerated by next `cargo test`).
# Only under real pressure (< half the free-space floor) or explicit --aggressive,
# since it forces a full test rebuild.
if [ "$AGG" -eq 1 ] || [ "$free_gb" -le $(( MIN_FREE_GB / 2 )) ]; then
  rm_path "$TARGET_DIR/debug"
else
  log "keeping target/debug (not under hard pressure; pass --aggressive to wipe test artifacts)"
fi

if [ "$DRY" -ne 1 ]; then
  new_gb="$(gb_of "$TARGET_DIR")"
  log "done — target now ${new_gb}G (was ${target_gb}G), free now $(df -BG --output=avail "$TARGET_DIR" 2>/dev/null | tail -1 | tr -dc '0-9')G"
fi
